import { FastFoodBrand, Transaction } from "@/types";

export const INITIAL_BRANDS: FastFoodBrand[] = [
  {
    id: "taco-bell",
    name: "Taco Bell",
    category: "Mexican",
    totalScore: 482,
    totalBoosts: 512,
    totalSabotages: 30,
    currentSlogan: "Baja Blast cures existential dread.",
    sloganAuthor: "@midnight_coder",
    location: "Irvine, CA 🌴",
    updatedAt: "2 mins ago",
    clicks: 1420,
    accentColor: "#9b51e0",
  },
  {
    id: "wendys",
    name: "Wendy's",
    category: "Burgers",
    totalScore: 479,
    totalBoosts: 495,
    totalSabotages: 16,
    currentSlogan: "Square beef because we don't cut corners.",
    sloganAuthor: "@frosty_fanatic",
    location: "Columbus, OH 🌰",
    updatedAt: "8 mins ago",
    clicks: 1289,
    accentColor: "#e53e3e",
  },
  {
    id: "in-n-out",
    name: "In-N-Out Burger",
    category: "Burgers",
    totalScore: 410,
    totalBoosts: 430,
    totalSabotages: 20,
    currentSlogan: "Animal style or you don't respect yourself.",
    sloganAuthor: "@cali_kingpin",
    location: "Los Angeles, CA ☀️",
    updatedAt: "14 mins ago",
    clicks: 980,
    accentColor: "#ecc94b",
  },
  {
    id: "mcdonalds",
    name: "McDonald's",
    category: "Burgers",
    totalScore: 365,
    totalBoosts: 420,
    totalSabotages: 55,
    currentSlogan: "The ice cream machine is permanently broken.",
    sloganAuthor: "@mcflurry_skeptic",
    location: "Chicago, IL 🏙️",
    updatedAt: "19 mins ago",
    clicks: 2100,
    accentColor: "#f6e05e",
  },
  {
    id: "chick-fil-a",
    name: "Chick-fil-A",
    category: "Chicken",
    totalScore: 340,
    totalBoosts: 355,
    totalSabotages: 15,
    currentSlogan: "My pleasure, except on Sundays.",
    sloganAuthor: "@waffle_fry_fiend",
    location: "Atlanta, GA 🍑",
    updatedAt: "25 mins ago",
    clicks: 860,
    accentColor: "#e53e3e",
  },
  {
    id: "popeyes",
    name: "Popeyes",
    category: "Chicken",
    totalScore: 310,
    totalBoosts: 330,
    totalSabotages: 20,
    currentSlogan: "Need 4 gallons of water for one biscuit.",
    sloganAuthor: "@spicy_crunch",
    location: "New Orleans, LA 🎷",
    updatedAt: "32 mins ago",
    clicks: 740,
    accentColor: "#dd6b20",
  },
  {
    id: "five-guys",
    name: "Five Guys",
    category: "Burgers",
    totalScore: 285,
    totalBoosts: 310,
    totalSabotages: 25,
    currentSlogan: "A small fries feeds an entire village.",
    sloganAuthor: "@peanut_gallery",
    location: "Arlington, VA 🥜",
    updatedAt: "40 mins ago",
    clicks: 690,
    accentColor: "#e53e3e",
  },
  {
    id: "burger-king",
    name: "Burger King",
    category: "Burgers",
    totalScore: 195,
    totalBoosts: 260,
    totalSabotages: 65,
    currentSlogan: "Have it your way, even if you regret it.",
    sloganAuthor: "@whopper_warrior",
    location: "Miami, FL 🌴",
    updatedAt: "1 hour ago",
    clicks: 530,
    accentColor: "#c53030",
  },
  {
    id: "panda-express",
    name: "Panda Express",
    category: "Late Night",
    totalScore: 180,
    totalBoosts: 195,
    totalSabotages: 15,
    currentSlogan: "Orange chicken is basically candy. I love it.",
    sloganAuthor: "@wok_star",
    location: "Glendale, CA 🥡",
    updatedAt: "1 hour ago",
    clicks: 420,
    accentColor: "#e53e3e",
  },
  {
    id: "subway",
    name: "Subway",
    category: "Sandwiches",
    totalScore: 84,
    totalBoosts: 190,
    totalSabotages: 106,
    currentSlogan: "The floor smell follows you home.",
    sloganAuthor: "@tuna_skeptic",
    location: "Milford, CT 🥖",
    updatedAt: "2 hours ago",
    clicks: 610,
    accentColor: "#38a169",
  },
  {
    id: "arbys",
    name: "Arby's",
    category: "Sandwiches",
    totalScore: 42,
    totalBoosts: 110,
    totalSabotages: 68,
    currentSlogan: "WE HAVE THE MEATS (for some reason).",
    sloganAuthor: "@curly_fry_advocate",
    location: "Boardman, OH 🥩",
    updatedAt: "3 hours ago",
    clicks: 340,
    accentColor: "#c53030",
  },
  {
    id: "jack-in-the-box",
    name: "Jack in the Box",
    category: "Late Night",
    totalScore: 35,
    totalBoosts: 90,
    totalSabotages: 55,
    currentSlogan: "Those 99c tacos are a biological miracle.",
    sloganAuthor: "@grease_fiend",
    location: "San Diego, CA 🌮",
    updatedAt: "4 hours ago",
    clicks: 310,
    accentColor: "#c53030",
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    brandId: "taco-bell",
    brandName: "Taco Bell",
    actionType: "BOOST",
    amount: 5,
    message: "Baja Blast cures existential dread.",
    author: "@midnight_coder",
    location: "Irvine, CA 🌴",
    timestamp: "2m ago",
    receiptNumber: "ORD-9412",
  },
  {
    id: "tx-1b",
    brandId: "taco-bell",
    brandName: "Taco Bell",
    actionType: "BOOST",
    amount: 2,
    message: "Cheesy Gordita Crunch is culinary art.",
    author: "@gordita_stan",
    location: "Austin, TX 🤠",
    timestamp: "6m ago",
    receiptNumber: "ORD-9411",
  },
  {
    id: "tx-1c",
    brandId: "taco-bell",
    brandName: "Taco Bell",
    actionType: "SABOTAGE",
    amount: 3,
    message: "My stomach has filed an official lawsuit.",
    author: "@pepto_warrior",
    location: "Miami, FL 🏖️",
    timestamp: "14m ago",
    receiptNumber: "ORD-9407",
  },
  {
    id: "tx-2",
    brandId: "subway",
    brandName: "Subway",
    actionType: "SABOTAGE",
    amount: 3,
    message: "The floor smell follows you home.",
    author: "@tuna_skeptic",
    location: "Milford, CT 🥖",
    timestamp: "5m ago",
    receiptNumber: "ORD-9410",
  },
  {
    id: "tx-2b",
    brandId: "subway",
    brandName: "Subway",
    actionType: "BOOST",
    amount: 1,
    message: "Raspberry cheesecake cookies slap though.",
    author: "@cookie_defender",
    location: "Denver, CO 🏔️",
    timestamp: "22m ago",
    receiptNumber: "ORD-9404",
  },
  {
    id: "tx-3",
    brandId: "wendys",
    brandName: "Wendy's",
    actionType: "BOOST",
    amount: 10,
    message: "Square beef because we don't cut corners.",
    author: "@frosty_fanatic",
    location: "Columbus, OH 🌰",
    timestamp: "8m ago",
    receiptNumber: "ORD-9409",
  },
  {
    id: "tx-3b",
    brandId: "wendys",
    brandName: "Wendy's",
    actionType: "BOOST",
    amount: 3,
    message: "Dipping spicy nuggets in chocolate frosty is elite.",
    author: "@dip_master",
    location: "Atlanta, GA 🍑",
    timestamp: "18m ago",
    receiptNumber: "ORD-9405",
  },
  {
    id: "tx-4",
    brandId: "mcdonalds",
    brandName: "McDonald's",
    actionType: "SABOTAGE",
    amount: 2,
    message: "Ice cream machine broken again.",
    author: "@mcflurry_skeptic",
    location: "Chicago, IL 🏙️",
    timestamp: "12m ago",
    receiptNumber: "ORD-9408",
  },
  {
    id: "tx-4b",
    brandId: "mcdonalds",
    brandName: "McDonald's",
    actionType: "BOOST",
    amount: 5,
    message: "Hash browns straight out of the fryer hit different.",
    author: "@breakfast_bandit",
    location: "New York, NY 🗽",
    timestamp: "25m ago",
    receiptNumber: "ORD-9403",
  },
  {
    id: "tx-5",
    brandId: "in-n-out",
    brandName: "In-N-Out Burger",
    actionType: "BOOST",
    amount: 5,
    message: "Animal style or you don't respect yourself.",
    author: "@cali_kingpin",
    location: "Los Angeles, CA ☀️",
    timestamp: "14m ago",
    receiptNumber: "ORD-9406",
  },
  {
    id: "tx-5b",
    brandId: "in-n-out",
    brandName: "In-N-Out Burger",
    actionType: "SABOTAGE",
    amount: 4,
    message: "The fries taste like cardboard styrofoam packing peanuts.",
    author: "@fry_critic",
    location: "Phoenix, AZ 🌵",
    timestamp: "30m ago",
    receiptNumber: "ORD-9401",
  },
  {
    id: "tx-6",
    brandId: "chick-fil-a",
    brandName: "Chick-fil-A",
    actionType: "BOOST",
    amount: 5,
    message: "My pleasure, except on Sundays.",
    author: "@waffle_fry_fiend",
    location: "Atlanta, GA 🍑",
    timestamp: "20m ago",
    receiptNumber: "ORD-9402",
  },
];
