import { FastFoodBrand, Transaction } from "@/types";

export const INITIAL_BRANDS: FastFoodBrand[] = [
  {
    id: "mcdonalds",
    name: "McDonald's",
    category: "Burgers",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#f6e05e",
  },
  {
    id: "taco-bell",
    name: "Taco Bell",
    category: "Mexican",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#9b51e0",
  },
  {
    id: "wendys",
    name: "Wendy's",
    category: "Burgers",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#e53e3e",
  },
  {
    id: "in-n-out",
    name: "In-N-Out Burger",
    category: "Burgers",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#ecc94b",
  },
  {
    id: "chick-fil-a",
    name: "Chick-fil-A",
    category: "Chicken",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#e53e3e",
  },
  {
    id: "popeyes",
    name: "Popeyes",
    category: "Chicken",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#dd6b20",
  },
  {
    id: "five-guys",
    name: "Five Guys",
    category: "Burgers",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#e53e3e",
  },
  {
    id: "burger-king",
    name: "Burger King",
    category: "Burgers",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#c53030",
  },
  {
    id: "raising-canes",
    name: "Raising Cane's",
    category: "Chicken",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#dd6b20",
  },
  {
    id: "culvers",
    name: "Culver's",
    category: "Burgers",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#3182ce",
  },
  {
    id: "panda-express",
    name: "Panda Express",
    category: "Late Night",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#e53e3e",
  },
  {
    id: "subway",
    name: "Subway",
    category: "Sandwiches",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#38a169",
  },
  {
    id: "arbys",
    name: "Arby's",
    category: "Sandwiches",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#c53030",
  },
  {
    id: "jack-in-the-box",
    name: "Jack in the Box",
    category: "Late Night",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#c53030",
  },
  {
    id: "sonic",
    name: "Sonic Drive-In",
    category: "Late Night",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#3182ce",
  },
  {
    id: "white-castle",
    name: "White Castle",
    category: "Late Night",
    totalScore: 0,
    totalBoosts: 0,
    totalSabotages: 0,
    currentSlogan: "Waiting for inaugural claim...",
    sloganAuthor: "Unclaimed",
    updatedAt: "Ready for launch",
    clicks: 0,
    accentColor: "#2b6cb0",
  },
];

// Clean launch state: 0 mock comments/orders
export const INITIAL_TRANSACTIONS: Transaction[] = [];
